config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  }

  devise_scope :customer do
    post 'public/customers/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root 'public/home#top'

  namespace :admin do
    resources :customers, :only => [:index, :show, :update, :edit]
    resources :reviews, :only => [:show, :destroy]
    get 'reviews/index/:id', to: 'reviews#index', as: 'admin_reviews'
    resources :comments, :only => [:destroy]
    get 'comments/index/:id', to: 'comments#index', as: 'admin_comments'
    resources :prefectures, :only => [:new, :create, :update, :edit, :destroy]
  end

  namespace :public do
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch ':id/customers/withdraw' => 'customers#withdraw'
    put 'customers/withdraw' => 'customers#withdraw'
    resources :customers, :only => [:show, :update, :edit]
    resources :reviews, :only => [:new, :create, :show, :update, :edit, :destroy]
    get 'reviews/index/:id', to: 'reviews#index', as: 'public_reviews'
    get 'reviews/venue/search', to: 'reviews#venue_search', as: 'venue_search'
    resources :comments, :only => [:create, :update, :edit, :destroy]
    get 'comments/index/:id', to: 'comments#index', as: 'public_comments'
    resources :products do
    collection do
      get :search
    end
  end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  validates :comment, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
    @customer = Customer.find(params[:id])
    @comments = @customer.comments.page(params[:page]).order(created_at: :desc)
  end

  def destroy
    comment = Comment.find(params[:id])
    @customer = comment.customer.id
    comment.destroy
    redirect_to admin_admin_comments_path(@customer)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container">

<div class="tytle">
 <h2><%= @customer.last_name %> <%= @customer.first_name %>さんのコメント一覧</h2>
</div>

<% @comments.each do |comment| %>
<div class="row comment_box">
 <div class="col-lg-1">
  <%= image_tag @customer.get_profile_image, size: "60x60" %>
 </div>
 <div class="col-lg-9 comment">
 <%= comment.comment %>
 </div>
 <div class="col-lg-2">
 <%= link_to '削除', admin_comment_path(comment.id), method: :delete, class: "btn btn-danger" %><br>
 </div>
 </div>
<% end %>
<%= paginate @comments %>
</div>