config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  }

  devise_scope :customer do
    post 'public/customers/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root 'public/home#top'

  namespace :admin do
    resources :customers, :only => [:index, :show, :update, :edit]
    resources :reviews, :only => [:show, :destroy]
    get 'reviews/index/:id', to: 'reviews#index', as: 'admin_reviews'
    resources :comments, :only => [:destroy]
    get 'comments/index/:id', to: 'comments#index', as: 'admin_comments'
    resources :prefectures, :only => [:new, :create, :update, :edit, :destroy]
  end

  namespace :public do
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch ':id/customers/withdraw' => 'customers#withdraw'
    put 'customers/withdraw' => 'customers#withdraw'
    resources :customers, :only => [:show, :update, :edit]
    resources :reviews, :only => [:new, :create, :show, :update, :edit, :destroy]
    get 'reviews/index/:id', to: 'reviews#index', as: 'public_reviews'
    get 'reviews/venue/search', to: 'reviews#venue_search', as: 'venue_search'
    resources :comments, :only => [:create, :update, :edit, :destroy]
    get 'comments/index/:id', to: 'comments#index', as: 'public_comments'
    resources :products do
    collection do
      get :search
    end
  end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :prefecture
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :nickname, presence: true
  validates :sex, presence: true
  validates :birthday, presence: true

  enum sex: { man: 0, woman: 1 }

  has_one_attached :profile_image

  def self.guest
  find_or_create_by!(email: 'aaa@aaa.com') do |user|
    user.password = SecureRandom.urlsafe_base64
    user.password_confirmation = user.password
    user.last_name = 'ゲスト'
    user.first_name = 'ユーザー'
    user.last_name_kana = 'ゲスト'
    user.first_name_kana = 'ユーザー'
    user.nickname = 'ゲスト'
    user.sex = 0
    user.birthday = Date.today
    user.prefecture_id = 1
    user.is_deleted = false
   end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image
    end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
    @reviews = @customer.reviews.all.limit(3).order(created_at: :desc)
    @comments = @customer.comments.all.limit(4).order(created_at: :desc)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :nickname, :sex, :birthday, :prefecture_id, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

<div class="tytle">
 <h2><%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報編集</h2>
</div>

<%= form_with model: @customer, url: admin_customer_path do |f| %>

<div class="field">
<%= f.label :id, '会員番号' %><br>
   <%= @customer.id %><br>
</div>

<div class="field">
<%= f.label :name, '氏名' %><br>
   <%= f.text_field :last_name, size: 30 %>  <%= f.text_field :first_name, size: 30 %><br>
</div>

<div class="field">
<%= f.label :name_kana, 'フリガナ' %><br>
   <%= f.text_field :last_name_kana, size: 30 %>  <%= f.text_field :first_name_kana, size: 30 %><br>
</div>

<div class="field">
<%= f.label :nickname, 'ニックネーム' %><br>
   <%= f.text_field :nickname, size: 40 %><br>
</div>

<div class="field">
<%= f.label :sex, '性別' %><br>
   <%= f.radio_button :sex, :man %>
   <%= f.label :sex, Customer.sexes_i18n[:man] %>
   <%= f.radio_button :sex, :woman %>
   <%= f.label :sex, Customer.sexes_i18n[:woman]%><br>
</div>

<div class="field">
<%= f.label :birthday, '生年月日' %><br>
   <%= f.date_select(
        :birthday,
        start_year: 1930,
        end_year: (Time.now.year),
        default: Date.new(1970, 1, 1)) %><br>
</div>

<div class="field">
<%= f.label :prefecture_name, '都道府県' %><br>
  <%= f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture_name, prompt:"選択してください" %><br>
</div>

<div class="field">
<%= f.label :email, 'メールアドレス' %><br>
   <%= f.text_field :email, size: 40 %><br>
</div>

<div class="field">
<%= f.label :is_deleted, 'ステータス' %><br>
   <%= f.radio_button :is_deleted, :false %>有効
   <%= f.radio_button :is_deleted, :true %>退会<br>
</div>

<div class="actions">
 <%= f.submit '更新', class: "btn btn-success w-50 mt-2" %>
</div>
<% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">

<div class="tytle">
 <h2>会員一覧</h2>
</div>

<table class ="table">
<thead>
<tr>
  <th>会員番号</th>
  <th>氏名</th>
  <th>メールアドレス</th>
  <th>ステータス</th>
</tr>
</thead>
<tbody>
  <% @customers.each do |customer| %>
<tr>
  <td><%= customer.id %></td>
  <td>
   <%= link_to admin_customer_path(customer.id) do %>
    <%= customer.last_name %><%= customer.first_name %>
   <% end %>
  </td>
  <td><%= customer.email %></td>
  <td>
    <% if customer.is_deleted == false %>
     有効
    <% else %>
     退会
    <% end %>
  </td>
</tr>
  <% end %>
</tbody>
</table>
 <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">

<div class="tytle">
 <h2><%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報</h2>
</div>

<h3>プロフィール</h3>
 <table class ="table">
  <tr>
    <th>会員番号</th>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <th>氏名</th>
    <td><%= @customer.last_name %> <%= @customer.first_name %></td>
  </tr>
  <tr>
    <th>フリガナ</th>
    <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
  </tr>
  <tr>
    <th>ニックネーム</th>
    <td><%= @customer.nickname %></td>
  </tr>
  <tr>
    <th>性別</th>
    <td>
      <% if @customer.sex == "man" %>
       男性
      <% else%>
       女性
      <% end %>
    </td>
  </tr>
  <tr>
    <th>生年月日</th>
    <td><%= @customer.birthday %></td>
  </tr>
  <tr>
    <th>都道府県</th>
    <td><%= @customer.prefecture.prefecture_name %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <th>ステータス</th>
     <td>
      <% if @customer.is_deleted == false %>
       有効
      <% else %>
       退会
      <% end %>
     </td>
  </tr>
 </table>

 <div class="actions">
  <%= link_to "編集", edit_admin_customer_path(@customer.id), class: "btn btn-success w-50 mt-2" %><br>
 </div>
<br>

<div class="row">
 <div class="col-lg-6">
<div class="tytle">
 <h4>最近投稿したレビュー</h4>
</div>
<% @reviews.each do |review| %>
<div class="reviewbox">
 <h5><%= review.venue %></h5>
 <%= review.comment %><br>
</div>
<% end %>
<div class="index_path">
<%= link_to ">全ての投稿を見る", admin_admin_reviews_path(@customer.id) %><br>
</div>
</div>

<div class="col-lg-6">
<div class="tytle">
 <h4>最近投稿したコメント</h4>
</div>
<% @comments.each do |comment| %>
<div class = "row comment_box">
 <div class = "col-lg-2">
 <%= image_tag @customer.get_profile_image, size: "60x60" %>
 </div>
 <div class = "col-lg-10">
 <%= comment.comment %><br>
 </div>
</div>
<% end %>
<div class="index_path">
<%= link_to ">全ての投稿を見る", admin_admin_comments_path(@customer.id) %>
</div>
</div>
</div>
</div>