config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  }

  devise_scope :customer do
    post 'public/customers/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root 'public/home#top'

  namespace :admin do
    resources :customers, :only => [:index, :show, :update, :edit]
    resources :reviews, :only => [:show, :destroy]
    get 'reviews/index/:id', to: 'reviews#index', as: 'admin_reviews'
    resources :comments, :only => [:destroy]
    get 'comments/index/:id', to: 'comments#index', as: 'admin_comments'
    resources :prefectures, :only => [:new, :create, :update, :edit, :destroy]
  end

  namespace :public do
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch ':id/customers/withdraw' => 'customers#withdraw'
    put 'customers/withdraw' => 'customers#withdraw'
    resources :customers, :only => [:show, :update, :edit]
    resources :reviews, :only => [:new, :create, :show, :update, :edit, :destroy]
    get 'reviews/index/:id', to: 'reviews#index', as: 'public_reviews'
    get 'reviews/venue/search', to: 'reviews#venue_search', as: 'venue_search'
    resources :comments, :only => [:create, :update, :edit, :destroy]
    get 'comments/index/:id', to: 'comments#index', as: 'public_comments'
    resources :products do
    collection do
      get :search
    end
  end
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  def index
    @customer = Customer.find(params[:id])
    @reviews = @customer.reviews.page(params[:page]).order(created_at: :desc)
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    customer = review.customer
    redirect_to admin_admin_reviews_path(customer.id)
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="container">

 <div class="tytle">
  <h2><%= @customer.last_name %> <%= @customer.first_name %>さんのレビュー一覧</h2>
 </div>

<% @reviews.each do |review| %>
<%= link_to admin_review_path(review.id) do %>
 <div class ="reviewbox">
  <h5><%= review.venue %></h5><br>
<% end %>
 <%= review.comment %><br>
 </div>
<% end %>
 <%= paginate @reviews %>
</div>

app/views/admin/reviews/show.html.erb
<div class="container">

<div class="tytle">
 <h2>レビュー詳細</h2>
</div>

<div class="row">
 <div class="col-lg-10">
  <h4><%= @review.venue %></h4>
 </div>
 <div class="col-lg-2">
  <%= @review.prefecture.prefecture_name %>
 </div>
</div>
<div class="row">
 <div class="col-lg-6">
  <h5 class="review_show">挙式会場</h5>
   <%= @review.chapel %><br>
  <br>
  <h5 class="review_show">披露宴会場</h5>
   <%= @review.reception %><br>
  <br>
  <h5 class="review_show">料理</h5>
   <%= @review.food %><br>
  <br>
 </div>
 <div class="col-lg-6">
  <h5 class="review_show">スタッフ</h5>
   <%= @review.staff %><br>
   <br>
   <h5 class="review_show">アクセス</h5>
   <%= @review.access %><br>
   <br>
   <h5 class="review_show">総合コメント</h5>
   <%= @review.comment %><br>
   </div>
  </div>

  <div class="row">
   <% if @review.images.attached? %>
    <% @review.images.each do |image| %>
     <%= image_tag image.variant(resize: '300x300') %>
    <% end %>
   <% end %><br>
  </div>


<div class="actions">
 <%= link_to 'このレビューを削除する', admin_review_path, method: :delete, class: "btn btn-danger w-50 mt-2" %>
</div>
</div>