config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  }

  devise_scope :customer do
    post 'public/customers/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root 'public/home#top'

  namespace :admin do
    resources :customers, :only => [:index, :show, :update, :edit]
    resources :reviews, :only => [:show, :destroy]
    get 'reviews/index/:id', to: 'reviews#index', as: 'admin_reviews'
    resources :comments, :only => [:destroy]
    get 'comments/index/:id', to: 'comments#index', as: 'admin_comments'
    resources :prefectures, :only => [:new, :create, :update, :edit, :destroy]
  end

  namespace :public do
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch ':id/customers/withdraw' => 'customers#withdraw'
    put 'customers/withdraw' => 'customers#withdraw'
    resources :customers, :only => [:show, :update, :edit]
    resources :reviews, :only => [:new, :create, :show, :update, :edit, :destroy]
    get 'reviews/index/:id', to: 'reviews#index', as: 'public_reviews'
    get 'reviews/venue/search', to: 'reviews#venue_search', as: 'venue_search'
    resources :comments, :only => [:create, :update, :edit, :destroy]
    get 'comments/index/:id', to: 'comments#index', as: 'public_comments'
    resources :products do
    collection do
      get :search
    end
  end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yui</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm" >
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <% if admin_signed_in? %>
          <a class="navbar-brand p-3" href="/admin/customers"><%= image_tag 'logo.png', :size => '100x50' %></a>
          <% else %>
          <a class="navbar-brand p-3" href="/"><%= image_tag 'logo.png', :size => '100x50' %></a>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <div class="search_form">
             <%= form_with url: public_venue_search_path, method: :get, local: true do |f| %>
               <%= f.text_field :keyword, placeholder: 'キーワードを入力...' %>
               <%= f.submit('検索する')  %>
             <% end %>
            </div>
            <li class="nav-item">
            <%= link_to "トップページ", root_path, class: 'nav-link text-dark' %>
            </li>
            <% if current_customer.email != "aaa@aaa.com" %>
            <li class="nav-item">
            <%= link_to "マイページ", public_customer_path(current_customer.id), class: 'nav-link text-dark' %>
            </li>
            <% end %>
            <li class="nav-item">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>

            <% elsif admin_signed_in? %>
            <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>

            <% else %>

            <li class="nav-item">
            <%= link_to "トップページ", root_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "ゲストログイン", public_customers_guest_sign_in_path, method: :post, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
            </li>
           <% end %>
           </ul>
          </div>
         </div>
        </nav>
       </header>
       <main class="mb-auto">
    <%= yield %>
  </body>
  <footer>
  </footer>
</html>